services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: 'redis:latest'
  client:
    image: "ronech/multi-client-up"
    mem_limit: 128m
    hostname: client
  server:
    image: "ronech/multi-server-up"
    mem_limit: 128m
    hostname: api
    environment:
#      - REDIS_HOST=$REDIS_HOST
#      - REDIS_PORT=$REDIS_PORT
#      - PGUSER=$PGUSER
#      - PGHOST=$PGHOST
#      - PGDATABASE=$PGDATABASE
#      - PGPASSWORD=$PGPASSWORD
#      - PGPORT=$PGPORT
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  worker:
    image: "ronech/multi-worker-up"
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: "ronech/multi-nginx-up"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"
